name: Build and deploy to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install .
    - name: Build package
      run: python -m build
    - name: Upload dist to artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  pypi-publish:
    name: Deploy to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyscoutfm
    permissions:
      id-token: write
    steps:
    - name: Download dist from artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
